# Servlet configuration
spring:
  application:
    name: game-service
  banner:
    location: classpath:banner.txt
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: classpath:database/main-changelog.xml
    enabled: true
server:
  servlet:
    context-path: /api
  port: 8082
  error:
    include-stacktrace: never
# JPA and Hibernate configuration
spring.datasource:
  url: jdbc:h2:file:./data/game-service
spring.jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: false
  properties:
    hibernate:
      format_sql: false
# Seed configuration
seed:
  enabled: true
  log-data: false
# Logging
logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 20MB
  file:
    name: "logs/game-service.log"
  level.cz.fi.muni.pa165: DEBUG
tasks:
  schedule:
    offset:
      match-schedule-offset: 1
    fetch-interval: 60
# Active MQ Artemis configuration
spring.artemis:
  user: artemis
  password: artemis
  broker-url: tcp://localhost:61616
# Location of other REST services
services.baseUrl:
  team-service: http://localhost:8081/api
