services:
  world-list-service:
    build:
      args:
        - SERVICE_NAME=world-list-service
    ports:
      - "8080:8080"
    volumes:
      - configs:/app/etc
  team-service:
    build:
      args:
        - SERVICE_NAME=team-service
    ports:
      - "8081:8081"
    volumes:
      - configs:/app/etc
    depends_on:
      - artemis
  game-service:
    build:
      args:
        - SERVICE_NAME=game-service
    ports:
      - "8082:8082"
    volumes:
      - configs:/app/etc
    depends_on:
      - artemis
  user-service:
    build:
      args:
        - SERVICE_NAME=user-service
    ports:
      - "8083:8083"
    volumes:
      - configs:/app/etc
    depends_on:
      - artemis
  oauth-client:
    build:
      args:
        - SERVICE_NAME=oauth-client
    ports:
      - "8084:8084"
    volumes:
      - configs:/app/etc
  artemis:
    image: apache/activemq-artemis:2.41.0-alpine
    environment:
      - ARTEMIS_USER=artemis
      - ARTEMIS_PASSWORD=artemis
    ports:
      - "61616:61616"
      - "8161:8161"
  prometheus:
    image: prom/prometheus:v3.4.0
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml
      - data:/prometheus
  grafana:
    image: grafana/grafana-enterprise:12.0.0
    ports:
      - "3000:3000"
    volumes:
      - data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./etc
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data