# Servlet configuration
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
  database:
    seed: true
    clear: false

spring:
  application:
    name: world-list-service
  banner:
    location: classpath:banner.txt
  # JPA and Hibernate configuration
  datasource:
    url: jdbc:h2:file:./data/worldlist-list-service
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:database/main-changelog.xml

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://id.muni.cz/oidc/introspect
          client-id: d57b3a8f-156e-46de-9f27-39c4daee05e1
          client-secret: fa228ebc-4d54-4cda-901e-4d6287f8b1652a9c9c44-73c9-4502-973f-bcdb4a8ec96a

  #Controllers config
  mvc:
    contentnegotiation:
      favor-parameter: false
      media-types:
        json: application/json

  #Jackson config
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true

# Logging
logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 20MB
  file:
    name: "logs/world-list-service.log"
  level.cz.fi.muni.pa165: DEBUG

management:
  security:
    token: EzGvDzOsbm-F7UtHCu6XmL0zyv3U9oqF
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true