# Servlet configuration
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
  database:
    seed: true
    clear: false

spring:
  application:
    name: world-list-service
  banner:
    location: classpath:banner.txt
  # JPA and Hibernate configuration
  datasource:
    url: jdbc:h2:file:./data/worldlist-list-service
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:database/main-changelog.xml

  #Controllers config
  mvc:
    contentnegotiation:
      favor-parameter: false
      media-types:
        json: application/json

  #Jackson config
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true

# Logging
logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 20MB
  file:
    name: "logs/world-list-service.log"
  level.cz.fi.muni.pa165: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true