scrape_configs:
  - job_name: 'spring-boot-microservices'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083' ]
    authorization:
      type: Bearer
      credentials: EzGvDzOsbm-F7UtHCu6XmL0zyv3U9oqF