spring:
  application:
    name: team-service
  banner:
    location: classpath:banner.txt
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: classpath:database/main-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://id.muni.cz/oidc/introspect
          client-id: d57b3a8f-156e-46de-9f27-39c4daee05e1
          client-secret: fa228ebc-4d54-4cda-901e-4d6287f8b1652a9c9c44-73c9-4502-973f-bcdb4a8ec96a

management:
  security:
    token: EzGvDzOsbm-F7UtHCu6XmL0zyv3U9oqF
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

server:
  servlet:
    context-path: /api
  port: 8081
  error:
    include-stacktrace: never


spring.datasource:
  url: jdbc:h2:file:./data/team-service
spring.jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: false
  properties:
    hibernate:
      format_sql: false
# Logging
logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 20MB
  file:
    name: "logs/team-service.log"
  level.cz.fi.muni.pa165: DEBUG
# Active MQ Artemis configuration
spring.artemis:
  user: artemis
  password: artemis
  broker-url: tcp://localhost:61616

