spring:
  application:
    name: team-service
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:h2:file:./data/team-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /api
  port: 8081
  error:
    include-stacktrace: never
