spring:
  application:
    name: user-service
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:h2:file:./data/user-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:database/main-changelog.xml
    enabled: true

server:
  servlet:
    context-path: /api
  port: 8083
  error:
    include-stacktrace: never
