{
 "title": "Spring Boot Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Server requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Buffer Memory used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total heap memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[5m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC eventes",
   "type": "timeseries",
   "description": "Number of garbage collection events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Pause Time Rate (5m)",
   "type": "timeseries",
   "description": "Average time per second spent in garbage collection over the last 5 minutes.\nUseful for identifying performance bottlenecks caused by frequent or long GC pauses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}