@startuml
left to right direction
skinparam packageStyle rectangle

actor User
actor Admin
actor UserService <<service>>
actor TeamService <<service>>
actor GameService <<service>>
actor WorldListService <<service>>

rectangle "Ice Hockey Manager" {
    usecase (Log in) as LogIn
    usecase (Register) as Register
    usecase (Update Profile) as UpdateProfile
    usecase (Buy players) as BuyPlayers
    usecase (Sell players) as SellPlayers
    usecase (Manage team) as ManageTeam
    usecase (Start friendly match) as FriendlyMatch
    usecase (Register team into a championship) as ChampionShipRegister
    usecase (Read match results) as ReadMatchResults
    usecase (Execute matches) as ExecuteMatches
    usecase (Publish results) as PublishMatchResults

    usecase (Buy budget package) as BuyBudgetPackage
    usecase (Manage budget packages) as ManageBudgetPackages

    usecase (Manage the world list of teams) as ManageWorldListTeams
    usecase (Manage the world list of players) as ManageWorldListPlayers
    usecase (Manage game championships) as ManageChampionsShips
    usecase (Manage users) as ManageUsers

    User -- LogIn
    User -- Register
    LogIn -|> Register : \t\t\t\t<<extends>>
    User -- UpdateProfile
    User -- BuyPlayers
    User -- SellPlayers
    User -- ManageTeam
    User -- FriendlyMatch
    User -- ChampionShipRegister
    User -- ReadMatchResults
    User -- BuyBudgetPackage
    Admin -- ManageWorldListTeams
    Admin -- ManageWorldListPlayers
    Admin -- ManageChampionsShips
    Admin -- ManageUsers
    Admin -- ManageBudgetPackages

    LogIn -- UserService
    Register -- UserService
    UpdateProfile -- UserService
    ManageUsers -- UserService

    BuyPlayers -- TeamService
    SellPlayers -- TeamService
    ManageTeam -- TeamService

    FriendlyMatch -- GameService
    ChampionShipRegister -- GameService
    ExecuteMatches -- GameService
    PublishMatchResults -- GameService

    ManageWorldListTeams -- WorldListService
    ManageWorldListPlayers -- WorldListService
    ManageChampionsShips -- WorldListService

}
@enduml
